version: "3"

networks:
  net:

services:

  # -------------------------------------------------------
  loop-alpine:
    image: alpine:latest
    command: /bin/sh -c "while true; do sleep 0.001; echo 'msg'; done;"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:22222
        gelf-compression-type: none
        tag: loop
    depends_on: 
      - logrouter
    networks: 
      - net

  logrouter:
    image: logrouter
    container_name: logrouter
    volumes:
      - ./logrouter-data:/usr/src/app/data
    environment: 
      - UDP_LISTEN_PORT=22222
      - UDP_REMOTE_PORT=33333
      - UDP_REMOTE_HOST=54.37.77.224
      - ACTIVE_BUFFER_MAX_SIZE=1M
    ports: 
      - 22222:22222/udp
      - 33333:33333/udp
    networks: 
      - net