version: "3"

networks:
  net:

services:

  # -------------------------------------------------------
  loop-alpine:
    image: alpine:latest
    container_name: loop-alpine
    command: /bin/sh -c "while true; do sleep 0.1; echo 'msg'; done;"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:22222
        gelf-compression-type: none
        tag: loop
    depends_on: 
      - logrouter
    networks: 
      - net

  logrouter:
    image: logrouter
    container_name: logrouter
    volumes:
      - ./logrouter-data:/usr/src/app/data
    environment: 
      - UDP_LISTEN_PORT=22222
    ports: 
      - 22222:22222/udp
    networks: 
      - net